language: node_js

sudo: true
addons:
  apt:
    packages:
      - oracle-java9-set-default
before_script:
  - sleep 10
node_js:
  - "8"
  - "10"
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.3.deb && sudo dpkg -i --force-confnew elasticsearch-6.2.3.deb && sudo service elasticsearch start
  - sudo -E /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu
  - sudo service elasticsearch restart
notifications:
  email:
    recipients:
      - claude.niederlender@inist.fr
      - jean-baptiste.genicot@inist.fr
      - conditordev@gmail.com
    on_success: change
on_failure: always
